### ISSUE TITLE
Add a link from main repo?

### ISSUE THREAD

**Issue by UsulPro** [sohamkamani/javascript-design-patterns-for-humans#1]
Hi! It's amazing! Thank you for translating it to Javascript! :tada: :boom: :confetti_ball:
Great work :thumbsup:

Just wanted to clarify this is the final work or still WIP and whether you are going to keep it up-to-date with the original project?
If it is ready, can it be worth to create a PR with a link to the main project? (Because I found it just by chance)

**Comment by sohamkamani** [comment]
Hey thanks! This repo is up to date with the original repo as of the last commit here. This is the final work, but I am always open to updating it whenever possible. 

Can you elaborate what you mean by creating a PR? The original repo is in PHP, and I dont think merging this entire repo with that one makes sense (if that is what you meant)

**Comment by UsulPro** [comment]
I mean add a link from original repo to this project.
Something like:

### Other programming languages:

[Javascript (ES6)](https://github.com/sohamkamani/javascript-design-patterns-for-humans)

**Comment by sohamkamani** [comment]
I contacted the owner of that repo... it seems they have their own plans for porting it to other languages unfortunately 🙁
